name       : python-levenshtein
version    : 0.12.2
release    : 7
source     :
    - https://pypi.io/packages/source/p/python-Levenshtein/python-Levenshtein-0.12.2.tar.gz : dc2395fbd148a1ab31090dd113c366695934b9e85fe5a4b2a032745efd0346f6
homepage   : https://github.com/ztane/python-Levenshtein
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python extension for computing string edit distances and similarities
description: |
    The Levenshtein Python C extension module contains functions for fast computation of Levenshtein distance and string similarity.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
