name       : python-levenshtein
version    : 0.12.0
release    : 2
source     :
    - https://pypi.python.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz : 033a11de5e3d19ea25c9302d11224e1a1898fe5abd23c61c7c360c25195e3eb1
license    : GPL-2.0
component  : programming.python
summary    : Python extension for computing string edit distances and similarities
description: |
    The Levenshtein Python C extension module contains functions for fast computation of:

      - Levenshtein (edit) distance, and edit operations
      - string similarity
      - approximate median strings, and generally string averaging
      - string sequence and set similarity

    It supports both normal and Unicode strings.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
