name       : python-levenshtein
version    : 0.20.8
release    : 9
source     :
    - https://pypi.io/packages/source/L/Levenshtein/Levenshtein-0.20.8.tar.gz : a8cc52849264d3aa6e16c9daca95a02d59e9496c86f18def7131413cfba617cc
homepage   : https://github.com/maxbachmann/Levenshtein
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python extension for computing string edit distances and similarities
description: |
    The Levenshtein Python C extension module contains functions for fast computation of Levenshtein distance and string similarity.
builddeps  :
    - pkgconfig(python3)
    - rapidfuzz-cpp
    - python-build
    - python-installer
    - python-packaging
    - python-scikit-build
    - python-wheel
rundeps    :
    - python-rapidfuzz
build      : |
    %python3_setup
install    : |
    %python3_install
